version: '3'
services:
  debugger:
    image: curlimages/curl
    command: tail -f /dev/null
    networks:
      - mvm-network

  balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mvm-network
    depends_on:
      - api

  api:
    build:
      context: ./api
    deploy:
      replicas: 3
    networks:
      - mvm-network

networks:
  mvm-network:
    driver: bridge
